spring.application.name=affable-bean-ui

spring.data.redis.host=mac
spring.data.redis.port=6379
spring.data.redis.password=admin@123

spring.datasource.url=jdbc:mysql://localhost:3306/affable_ui
spring.datasource.username=root
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false
server.port=0
eureka.client.service-url.defaultZone=http://localhost:8083/eureka


