spring.application.name=affable-bean-gateway
server.port=8080
#affable-bean-backend
spring.cloud.gateway.server.webmvc.routes[0].id=affablebean-backend
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AFFABLE-BEAN-BACKEND
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/backend/**
#affable-bean-ui
spring.cloud.gateway.server.webmvc.routes[1].id=affablebean-ui-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AFFABLE-BEAN-UI
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/affable-bean/ui/**,/css/**,/images/**
#distributed-security-demo
spring.cloud.gateway.server.webmvc.routes[2].id=jwt-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://DISTRIBUTED-SECURITY-DEMO
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/auth/**,/api/jwt/**

#inventory-service
spring.cloud.gateway.server.webmvc.routes[3].id=inventory
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/inventory/**,/ui/inventory/**,/image/**
#payment-service
spring.cloud.gateway.server.webmvc.routes[4].id=payment
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/payment/**
#order-service
spring.cloud.gateway.server.webmvc.routes[5].id=order-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/order/**

eureka.client.service-url.defaultZone=http://localhost:8083/eureka






