spring.application.name=order-service

spring.datasource.url=jdbc:mysql://localhost:3306/affable_order
spring.datasource.username=root
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.virtual-host=/



server.port=0

eureka.client.service-url.defaultZone=http://localhost:8083/eureka